### PR TITLE
Import csv

### LINKED ISSUE #7: Build rake task to import csv
Build rake task to import CSV file into appropriate tables:
- olympians
- [ ] name
- [ ] sex
- [ ] age
- [ ] weight

- teams
- [ ] name

- sports
- [ ] name

- events
- [ ] name

### PR DESCRIPTION
**Pull request by sejinkim1904**
- Able to run task `rails import:csv` to import all CSV data into appropriate table including: 
  - Olympians
  - Teams
  - Sports
  - Events
  - OlympianSports
  - OlympianEvents 
 
- All models tested for relations

- Closes #7

### CODE REVIEW

**Comment by sejinkim1904** [comment]
@tbierwirth I wasn't able to implement `active-import` due to some of the associations and duplicate entries for some columns. Taking around 30 seconds to import everything into 6 tables. Were you able to find a way to make this process faster?

**Comment by tbierwirth** [comment]
Mine takes about the same, I was using a simple CSV for_each approach to create all the records/associations for each row.  Apologies for the delay in getting back to you.

**Comment by sejinkim1904** [comment]
@tbierwirth No worries, I understand we're all busy at the moment. I ended up removing OlympianSport table and adding sport_id to olympians after realizing they only have one sport

**Comment by sejinkim1904** [comment]
@tbierwirth Importing the csv into production took two minutes lol

**Pull request merged**
